-- MySQL Script generated by MySQL Workbench
-- Mon Aug 25 13:20:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `cvcrm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cvcrm` ;

-- -----------------------------------------------------
-- Table `cvcrm`.`cv_reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvcrm`.`cv_reservas` (
  `idreserva` BIGINT NOT NULL,
  `referencia` VARCHAR(32) NULL DEFAULT NULL,
  `referencia_data` DATETIME NULL DEFAULT NULL,
  `ativo` CHAR(1) NULL DEFAULT NULL,
  `codigointerno` VARCHAR(64) NULL DEFAULT NULL,
  `numero_venda` VARCHAR(64) NULL DEFAULT NULL,
  `aprovada` VARCHAR(8) NULL DEFAULT NULL,
  `data_cad` DATETIME NULL DEFAULT NULL,
  `data_venda` DATETIME NULL DEFAULT NULL,
  `situacao` VARCHAR(64) NULL DEFAULT NULL,
  `idsituacao` INT NULL DEFAULT NULL,
  `situacao_comercial` VARCHAR(128) NULL DEFAULT NULL,
  `idempreendimento` BIGINT NULL DEFAULT NULL,
  `codigointerno_empreendimento` VARCHAR(64) NULL DEFAULT NULL,
  `empreendimento` VARCHAR(255) NULL DEFAULT NULL,
  `data_entrega_chaves_contrato_cliente` DATE NULL DEFAULT NULL,
  `etapa` VARCHAR(64) NULL DEFAULT NULL,
  `bloco` VARCHAR(64) NULL DEFAULT NULL,
  `unidade` VARCHAR(64) NULL DEFAULT NULL,
  `regiao` VARCHAR(64) NULL DEFAULT NULL,
  `venda` VARCHAR(8) NULL DEFAULT NULL,
  `idcliente` BIGINT NULL DEFAULT NULL,
  `documento_cliente` VARCHAR(32) NULL DEFAULT NULL,
  `cliente` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `cidade` VARCHAR(128) NULL DEFAULT NULL,
  `cep_cliente` VARCHAR(16) NULL DEFAULT NULL,
  `renda` DECIMAL(14,2) NULL DEFAULT NULL,
  `sexo` VARCHAR(32) NULL DEFAULT NULL,
  `idade` INT NULL DEFAULT NULL,
  `estado_civil` VARCHAR(64) NULL DEFAULT NULL,
  `idcorretor` BIGINT NULL DEFAULT NULL,
  `corretor` VARCHAR(255) NULL DEFAULT NULL,
  `idimobiliaria` BIGINT NULL DEFAULT NULL,
  `imobiliaria` VARCHAR(255) NULL DEFAULT NULL,
  `idtime` INT NULL DEFAULT NULL,
  `nome_time` VARCHAR(255) NULL DEFAULT NULL,
  `valor_contrato` DECIMAL(14,2) NULL DEFAULT NULL,
  `vencimento` DATETIME NULL DEFAULT NULL,
  `campanha` VARCHAR(255) NULL DEFAULT NULL,
  `cessao` VARCHAR(8) NULL DEFAULT NULL,
  `motivo_cancelamento` VARCHAR(255) NULL DEFAULT NULL,
  `data_cancelamento` DATETIME NULL DEFAULT NULL,
  `espacos_complementares` VARCHAR(255) NULL DEFAULT NULL,
  `idlead` VARCHAR(64) NULL DEFAULT NULL,
  `data_ultima_alteracao_situacao` DATETIME NULL DEFAULT NULL,
  `idempresa_correspondente` BIGINT NULL DEFAULT NULL,
  `empresa_correspondente` VARCHAR(255) NULL DEFAULT NULL,
  `valor_fgts` DECIMAL(14,2) NULL DEFAULT NULL,
  `valor_financiamento` DECIMAL(14,2) NULL DEFAULT NULL,
  `valor_subsidio` DECIMAL(14,2) NULL DEFAULT NULL,
  `nome_usuario` VARCHAR(255) NULL DEFAULT NULL,
  `idunidade` BIGINT NULL DEFAULT NULL,
  `idprecadastro` BIGINT NULL DEFAULT NULL,
  `idmidia` BIGINT NULL DEFAULT NULL,
  `midia` VARCHAR(255) NULL DEFAULT NULL,
  `descricao_motivo_cancelamento` VARCHAR(255) NULL DEFAULT NULL,
  `idsituacao_anterior` INT NULL DEFAULT NULL,
  `situacao_anterior` VARCHAR(64) NULL DEFAULT NULL,
  `idtabela` BIGINT NULL DEFAULT NULL,
  `nometabela` VARCHAR(255) NULL DEFAULT NULL,
  `codigointernotabela` VARCHAR(64) NULL DEFAULT NULL,
  `idtipo_tabela` INT NULL DEFAULT NULL,
  `tipo_tabela` VARCHAR(64) NULL DEFAULT NULL,
  `data_contrato` DATE NULL DEFAULT NULL,
  `valor_proposta` DECIMAL(14,2) NULL DEFAULT NULL,
  `vpl_reserva` DECIMAL(14,2) NULL DEFAULT NULL,
  `vgv_tabela` DECIMAL(14,2) NULL DEFAULT NULL,
  `vpl_tabela` DECIMAL(14,2) NULL DEFAULT NULL,
  `usuario_aprovacao` VARCHAR(255) NULL DEFAULT NULL,
  `data_aprovacao` DATE NULL DEFAULT NULL,
  `juros_condicao_aprovada` DECIMAL(9,4) NULL DEFAULT NULL,
  `juros_apos_entrega_condicao_aprovada` DECIMAL(9,4) NULL DEFAULT NULL,
  `idtabela_condicao_aprovada` BIGINT NULL DEFAULT NULL,
  `data_primeira_aprovacao` DATE NULL DEFAULT NULL,
  `aprovacao_absoluto` DECIMAL(14,2) NULL DEFAULT NULL,
  `aprovacao_vpl_valor` DECIMAL(14,2) NULL DEFAULT NULL,
  `idtipovenda` INT NULL DEFAULT NULL,
  `tipovenda` VARCHAR(64) NULL DEFAULT NULL,
  `idgrupo` INT NULL DEFAULT NULL,
  `grupo` VARCHAR(255) NULL DEFAULT NULL,
  `data_modificacao` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idreserva`),
  INDEX `idx_reservas_datas` (`data_cad` ASC, `data_venda` ASC) VISIBLE,
  INDEX `idx_reservas_lead` (`idlead` ASC) VISIBLE,
  INDEX `idx_reservas_emp` (`idempreendimento` ASC) VISIBLE,
  INDEX `idx_reservas_idsituacao` (`idsituacao` ASC) VISIBLE,
  INDEX `idx_reservas_idunidade` (`idunidade` ASC) VISIBLE,
  INDEX `idx_reservas_datas_ext` (`data_cancelamento` ASC, `data_ultima_alteracao_situacao` ASC, `data_modificacao` ASC) VISIBLE,
  INDEX `idx_reservas_documento` (`documento_cliente` ASC) VISIBLE,
  INDEX `idx_reservas_email` (`email` ASC) VISIBLE,
  INDEX `idx_reservas_corretor` (`idcorretor` ASC) VISIBLE,
  INDEX `idx_reservas_situacao_comercial` (`situacao_comercial` ASC) VISIBLE,
  INDEX `idx_reservas_numero_venda` (`numero_venda` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cvcrm`.`cv_reservas_campos_adicionais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvcrm`.`cv_reservas_campos_adicionais` (
  `idreserva` BIGINT NOT NULL,
  `referencia` VARCHAR(32) NULL DEFAULT NULL,
  `referencia_data` DATETIME NULL DEFAULT NULL,
  `idcampo_valores` BIGINT NOT NULL,
  `idcampo` BIGINT NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `valor` TEXT NULL DEFAULT NULL,
  `tipo` VARCHAR(64) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idreserva`, `idcampo_valores`),
  INDEX `idx_cvrca_idcampo` (`idcampo` ASC) VISIBLE,
  INDEX `idx_cvrca_idreserva` (`idreserva` ASC) VISIBLE,
  INDEX `idx_cvrca_nome` (`nome` ASC) VISIBLE,
  INDEX `idx_cvrca_tipo` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cvcrm`.`cv_reservas_campos_adicionais_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvcrm`.`cv_reservas_campos_adicionais_contrato` (
  `idreservacontratocampoadicional` BIGINT NOT NULL,
  `idreserva` BIGINT NOT NULL,
  `referencia` VARCHAR(32) NULL DEFAULT NULL,
  `referencia_data` DATETIME NULL DEFAULT NULL,
  `idcampo` BIGINT NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `valor` TEXT NULL DEFAULT NULL,
  `tipo` VARCHAR(64) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idreservacontratocampoadicional`),
  INDEX `idx_cvrcac_idreserva` (`idreserva` ASC) VISIBLE,
  INDEX `idx_cvrcac_idcampo` (`idcampo` ASC) VISIBLE,
  INDEX `idx_cvrcac_nome` (`nome` ASC) VISIBLE,
  INDEX `idx_cvrcac_tipo` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




--- Tabela precadastros

CREATE TABLE IF NOT EXISTS `cv_precadastros` (
  `idprecadastro`                    BIGINT        NOT NULL,

  `referencia`                       VARCHAR(32)   NULL,
  `referencia_data`                  DATETIME      NULL,
  `ativo`                            CHAR(1)       NULL,
  `codigointerno`                    VARCHAR(64)   NULL,
  `idsituacao`                       INT           NULL,
  `situacao`                         VARCHAR(64)   NULL,
  `condicao_aprovada`                CHAR(1)       NULL,        -- "S"/"N"
  `idempreendimento`                 BIGINT        NULL,
  `empreendimento`                   VARCHAR(255)  NULL,
  `idunidade`                        BIGINT        NULL,
  `unidade`                          VARCHAR(64)   NULL,
  `idcorretor`                       BIGINT        NULL,
  `corretor`                         VARCHAR(255)  NULL,
  `idimobiliaria`                    BIGINT        NULL,
  `imobiliaria`                      VARCHAR(255)  NULL,
  `idempresa`                        BIGINT        NULL,
  `empresa`                          VARCHAR(255)  NULL,
  `pessoa`                           VARCHAR(255)  NULL,
  `cep_cliente`                      VARCHAR(16)   NULL,
  `renda_cliente_principal`          DECIMAL(14,2) NULL,
  `idusuario_correspondente`         BIGINT        NULL,
  `usuario_correspondente`           VARCHAR(255)  NULL,
  `idpessoa`                         BIGINT        NULL,
  `idlead`                           VARCHAR(64)   NULL,        -- valores podem vir separados por vírgula
  `valor_avaliacao`                  DECIMAL(14,2) NULL,
  `valor_aprovado`                   DECIMAL(14,2) NULL,
  `valor_subsidio`                   DECIMAL(14,2) NULL,
  `valor_total`                      DECIMAL(14,2) NULL,
  `valor_fgts`                       DECIMAL(14,2) NULL,
  `saldo_devedor`                    DECIMAL(14,2) NULL,
  `prazo`                            INT           NULL,        -- ex.: meses (quando aplicável)
  `observacoes`                      TEXT          NULL,
  `tabela`                           VARCHAR(64)   NULL,
  `valor_prestacao`                  DECIMAL(14,2) NULL,
  `carta_credito`                    VARCHAR(64)   NULL,
  `vencimento_aprovacao`             DATE          NULL,
  `idmotivo_reprovacao`              INT           NULL,
  `motivo_reprovacao`                VARCHAR(255)  NULL,
  `descricao_motivo_reprovacao`      VARCHAR(255)  NULL,
  `idmotivo_cancelamento`            INT           NULL,
  `motivo_cancelamento`              VARCHAR(255)  NULL,
  `descricao_motivo_cancelamento`    VARCHAR(255)  NULL,
  `sla_vencimento`                   INT           NULL,
  `data_cad`                         DATETIME      NULL,
  `empresa_correspondente`           VARCHAR(255)  NULL,
  `idsituacao_anterior`              INT           NULL,
  `situacao_anterior`                VARCHAR(64)   NULL,
  `data_ultima_alteracao_situacao`   DATETIME      NULL,
  `idintencao_compra`                INT           NULL,
  `intencao_compra`                  VARCHAR(255)  NULL,
  `renda_total`                      DECIMAL(14,2) NULL,
  `updated_at`                       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idprecadastro`),

  -- Índices úteis
  KEY `idx_pre_data_cad`              (`data_cad`),
  KEY `idx_pre_idsituacao`            (`idsituacao`),
  KEY `idx_pre_idcorretor`            (`idcorretor`),
  KEY `idx_pre_idimobiliaria`         (`idimobiliaria`),
  KEY `idx_pre_idempresa`             (`idempresa`),
  KEY `idx_pre_idunidade`             (`idunidade`),
  KEY `idx_pre_vencimento_aprovacao`  (`vencimento_aprovacao`),
  KEY `idx_pre_idlead`                (`idlead`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Tabela filha: cv_precadastros_campos_adicionais
-- Mapeia o array "campos_adicionais"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cv_precadastros_campos_adicionais` (
  `idprecadastro`        BIGINT        NOT NULL,
  `referencia`           VARCHAR(32)   NULL,
  `referencia_data`      DATETIME      NULL,
  `idcampo_valores`      BIGINT        NOT NULL,
  `idcampo`              BIGINT        NULL,
  `nome`                 VARCHAR(255)  NULL,
  `valor`                TEXT          NULL,
  `tipo`                 VARCHAR(64)   NULL,
  `created_at`           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`idprecadastro`, `idcampo_valores`),
  KEY `idx_cvpca_idcampo`  (`idcampo`),
  KEY `idx_cvpca_nome`     (`nome`),
  KEY `idx_cvpca_tipo`     (`tipo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


--- TABELA VISITAS


-- Tabela base: cv_visitas
CREATE TABLE IF NOT EXISTS `cv_visitas` (
  `idtarefa`                          BIGINT       NOT NULL,            -- PK (id da tarefa/visita)
  `referencia`                        VARCHAR(32)  NULL,
  `referencia_data`                   DATETIME     NULL,
  `ativo`                             CHAR(1)      NULL,                -- 'S'/'N'

  `data_cad`                          DATETIME     NULL,
  `data`                              DATETIME     NULL,
  `situacao`                          VARCHAR(64)  NULL,

  `idresponsavel`                     BIGINT       NULL,
  `tipo_responsavel`                  CHAR(1)      NULL,                -- ex.: 'C'
  `responsavel`                       VARCHAR(255) NULL,

  `funcionalidade`                    VARCHAR(64)  NULL,                -- ex.: 'lead'
  `idlead`                            VARCHAR(64)  NULL,                -- string p/ tolerar variantes

  `idinteracao`                       BIGINT       NULL,
  `tipo_interacao`                    VARCHAR(64)  NULL,                -- ex.: 'Visita'
  `data_conclusao`                    DATETIME     NULL,

  `idtipo_visita`                     INT          NULL,
  `nome_tipo_visita`                  VARCHAR(255) NULL,
  `visita_virtual`                    CHAR(1)      NULL,                -- 'S'/'N'

  `pdv`                               VARCHAR(255) NULL,
  `painel_pdv`                        CHAR(1)      NULL,                -- 'S'/'N'

  `idresponsavel_por_criar_visita`    BIGINT       NULL,
  `responsavel_por_criar_visita`      VARCHAR(255) NULL,

  `idempreendimento`                  BIGINT       NULL,
  `nome_empreendimento`               VARCHAR(255) NULL,

  `updated_at`                        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
                                                 ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (`idtarefa`),

  -- Índices práticos de consulta
  KEY `idx_visitas_datas`            (`data_cad`,`data`,`data_conclusao`),
  KEY `idx_visitas_idlead`           (`idlead`),
  KEY `idx_visitas_idresponsavel`    (`idresponsavel`),
  KEY `idx_visitas_interacao`        (`idinteracao`,`tipo_interacao`),
  KEY `idx_visitas_idtipo`           (`idtipo_visita`),
  KEY `idx_visitas_idemp`            (`idempreendimento`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
